spring.application.name=api

# H2 Database configuration
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/testdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# Enable H2 console 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate auto-create tables
spring.jpa.hibernate.ddl-auto=update

# Optional: shows exactly what SQL statements are being run
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
