
export interface University { id: number; name: string; nameAr: string; nameZh: string; nameMs: string;  location: string; locationAr: string; locationZh: string; locationMs: string;  state: string; logoUrl: string; isPrivate: boolean; freeOfferLetter: boolean; courseCount: number; ranking: string; aboutEn: string; aboutAr: string; aboutZh: string; aboutMs: string;  heroImage: string; videoUrl: string; videoUrlAr: string; videoUrlZh: string; videoUrlMs: string;  galleryUrl1: string; galleryUrl2: string; galleryUrl3: string; galleryUrl4: string; bannerUrl: string; locationMapUrl: string; scholarshipDescEn: string; scholarshipDescAr: string; scholarshipDescZh: string; scholarshipDescMs: string;  scholarshipDiscount: string; scholarshipCriteria: string; admissionUndergradEn: string; admissionUndergradAr: string; admissionUndergradZh: string; admissionUndergradMs: string;  admissionPostgradEn: string; admissionPostgradAr: string; admissionPostgradZh: string; admissionPostgradMs: string;  registrationFeeMyr: number; visaFeeMyr: number; insuranceFeeMyr: number; depositFeeMyr: number; nextIntakeMonths: string; registrationDeadline?: string; }
export interface LanguageCenter { id: number; name: string; nameAr: string; nameZh: string; nameMs: string;  location: string; locationAr: string; locationZh: string; locationMs: string;  state: string; logoUrl: string; aboutEn: string; aboutAr: string; aboutZh: string; aboutMs: string;  heroImage: string; videoUrl: string; videoUrlAr: string; videoUrlZh: string; videoUrlMs: string;  galleryUrl1: string; galleryUrl2: string; galleryUrl3: string; galleryUrl4: string; bannerUrl: string; locationMapUrl: string; scholarshipDescEn: string; scholarshipDescAr: string; scholarshipDescZh: string; scholarshipDescMs: string;  scholarshipDiscount: string; scholarshipCriteria: string; admissionUndergradEn: string; admissionUndergradAr: string; admissionUndergradZh: string; admissionUndergradMs: string;  admissionPostgradEn: string; admissionPostgradAr: string; admissionPostgradZh: string; admissionPostgradMs: string;  registrationFeeMyr: number; visaFeeMyr: number; insuranceFeeMyr: number; depositFeeMyr: number; nextIntakeMonths: string; registrationDeadline?: string; }
export interface Course { id: number; titleEn: string; titleAr: string; titleZh: string; titleMs: string;  facultyEn: string; facultyAr: string; facultyZh: string; facultyMs: string;  level: string; levelAr: string; levelZh: string; levelMs: string;  universityId: number; universityName: string; universityNameAr: string; universityNameZh: string; universityNameMs: string;  feeMyr: number; duration: string; durationAr: string; durationZh: string; durationMs: string;  intakes: string; intakesAr: string; intakesZh: string; intakesMs: string;  }
export interface Testimonial { id: number; studentName: string; studentNameZh: string; studentNameMs: string;  universityName: string; universityNameAr: string; universityNameZh: string; universityNameMs: string;  reviewText: string; reviewTextAr: string; reviewTextZh: string; reviewTextMs: string;  rating: number; }
export interface BlogPost { id: number; title: string; titleAr: string; titleZh: string; titleMs: string;  category: string; categoryAr: string; categoryZh: string; categoryMs: string;  date: string; imageUrl: string; videoUrl?: string; videoUrlAr?: string; videoUrlZh?: string; videoUrlMs?: string; excerpt: string; excerptAr: string; excerptZh: string; excerptMs: string;  contentEn: string; contentAr: string; contentZh: string; contentMs: string;  published: boolean; }
export interface SiteSettings { siteName: string; siteNameAr: string; whatsappNumber: string; email: string; phone: string; address: string; }

export const API = `${process.env.NEXT_PUBLIC_API_URL || "https://yaalmalegacy.com/api"}`;

export const authFetch = (url: string, options: any = {}) => {
  const token = typeof window !== 'undefined' ? localStorage.getItem('admin_token') : null;
  const headers = { ...options.headers };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }
  return fetch(url, { ...options, headers });
};
